version: 3
dotenv: ['.env']

vars:
  BINARY_NAME: esxi-lab-scheduler
  REMOTE_PATH: /opt/esxi-lab
  SERVICE_NAME: esxi-lab-scheduler

tasks:
  default:
    desc: Deploy locally with docker-compose (default)
    cmds:
      - task: dev-up

  dev-build:
    desc: Build Docker image for local deployment
    cmds:
      - docker-compose build scheduler

  dev-up:
    desc: Start scheduler with docker-compose
    deps: [dev-build]
    cmds:
      - mkdir -p data
      - docker-compose up -d
      - echo "✓ Scheduler deployed locally with docker-compose"
      - echo "View logs:task dev-logs"
      - echo "Check status:task dev-status"

  dev-down:
    desc: Stop and remove all containers
    cmds:
      - docker-compose down
      - echo "✓ Scheduler stopped"

  dev-restart:
    desc: Restart the scheduler
    cmds:
      - docker-compose restart scheduler
      - echo "✓ Scheduler restarted"

  dev-logs:
    desc: View scheduler logs
    cmds:
      - docker-compose logs -f scheduler

  dev-logs-tail:
    desc: View last 50 lines of scheduler logs
    cmds:
      - docker-compose logs --tail=50 scheduler

  dev-logs-cron:
    desc: View cron logs
    cmds:
      - docker-compose logs -f cron

  dev-status:
    desc: Check container status
    cmds:
      - docker-compose ps

  dev-clean:
    desc: Stop containers and remove volumes
    cmds:
      - docker-compose down -v
      - rm -rf data
      - echo "✓ Local deployment cleaned"

  dev-exec:
    desc: Execute scheduler once manually
    cmds:
      - docker-compose run --rm scheduler /app/scheduler

  dev-test:
    desc: Build and test the scheduler locally
    cmds:
      - task: dev-build
      - docker-compose run --rm scheduler /app/scheduler
      - echo "✓ Test run completed. Check output above for errors."

  dev-verify-config:
    desc: Verify configuration loads correctly (fast check)
    cmds:
      - task: dev-build
      - echo "Testing configuration loading..."
      - docker-compose run --rm scheduler sh -c "cat /app/config/user_config.toml && echo '\n--- Config file loaded successfully ---'"

  dev-shell:
    desc: Open shell in scheduler container (debug)
    cmds:
      - docker-compose exec scheduler sh

  ssh-keygen:
    desc: Generate SSH key and upload to remote server for passwordless access
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
      KEY_PATH: '{{.HOME}}/.ssh/id_rsa_esxi_lab'
    cmds:
      - |
        if [ ! -f {{.KEY_PATH}} ]; then
          echo "Generating new SSH key..."
          ssh-keygen -t rsa -b 4096 -f {{.KEY_PATH}} -N "" -C "esxi-lab-deployment"
        else
          echo "SSH key already exists at {{.KEY_PATH}}"
        fi
      - echo "Uploading SSH key to {{.USER}}@{{.HOST}}:{{.PORT}}"
      - ssh-copy-id -i {{.KEY_PATH}}.pub -p {{.PORT}} {{.USER}}@{{.HOST}}
      - echo "SSH key configured! Test with ssh -i {{.KEY_PATH}} -p {{.PORT}} {{.USER}}@{{.HOST}}"
      - echo "Add to your ~/.ssh/config:"
      - |
        echo "Host esxi-lab"
        echo "  HostName {{.HOST}}"
        echo "  Port {{.PORT}}"
        echo "  User {{.USER}}"
        echo "  IdentityFile {{.KEY_PATH}}"

  setup-sudo:
    desc: Configure passwordless sudo for deployment user (requires password once)
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - echo "Configuring passwordless sudo for {{.USER}} on {{.HOST}}"
      - |
        ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "echo '{{.USER}} ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/{{.USER}} > /dev/null && sudo chmod 0440 /etc/sudoers.d/{{.USER}}"
      - echo "Passwordless sudo configured! Future deployments won't require password."

  setup-logging:
    desc: Configure journald to retain logs for 7 days
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - echo "Configuring journald log retention (7 days) on {{.HOST}}"
      - |
        ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo mkdir -p /etc/systemd/journald.conf.d && sudo tee /etc/systemd/journald.conf.d/retention.conf > /dev/null <<EOF
        [Journal]
        Storage=persistent
        MaxRetentionSec=7d
        SystemMaxUse=500M
        EOF"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl restart systemd-journald"
      - echo "Log retention configured! Logs will be kept for 7 days."

  build:
    desc: Build the scheduler binary
    dir: api
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../{{.BINARY_NAME}} ./cmd/server/main.go
    sources:
      - api/**/*.go
    generates:
      - "{{.BINARY_NAME}}"

  deploy:
    desc: Deploy scheduler to remote server via SSH (requires DEPLOY_USER, DEPLOY_HOST, DEPLOY_PORT env vars)
    deps: [build]
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - echo "Deploying to {{.USER}}@{{.HOST}}:{{.PORT}}"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo mkdir -p {{.REMOTE_PATH}} && sudo chown {{.USER}}:{{.USER}} {{.REMOTE_PATH}}"
      - scp -P {{.PORT}} {{.BINARY_NAME}} {{.USER}}@{{.HOST}}:{{.REMOTE_PATH}}/{{.BINARY_NAME}}
      - scp -P {{.PORT}} .env {{.USER}}@{{.HOST}}:{{.REMOTE_PATH}}/.env
      - scp -P {{.PORT}} api/data/user_config.toml {{.USER}}@{{.HOST}}:{{.REMOTE_PATH}}/user_config.toml
      - scp -P {{.PORT}} infra/terraform/service-account.json {{.USER}}@{{.HOST}}:{{.REMOTE_PATH}}/service-account.json
      - |
        ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo tee /etc/systemd/system/{{.SERVICE_NAME}}.service > /dev/null <<EOF
        [Unit]
        Description=ESXi Lab Scheduler
        After=network.target

        [Service]
        Type=oneshot
        User={{.USER}}
        WorkingDirectory={{.REMOTE_PATH}}
        Environment=CONFIG_PATH={{.REMOTE_PATH}}/user_config.toml
        EnvironmentFile={{.REMOTE_PATH}}/.env
        ExecStart={{.REMOTE_PATH}}/{{.BINARY_NAME}}
        StandardOutput=journal
        StandardError=journal
        SyslogIdentifier={{.SERVICE_NAME}}

        [Install]
        WantedBy=multi-user.target
        EOF"
      - |
        ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo tee /etc/systemd/system/{{.SERVICE_NAME}}.timer > /dev/null <<EOF
        [Unit]
        Description=ESXi Lab Scheduler Timer (runs at the start of every hour)

        [Timer]
        OnCalendar=*:00:00
        AccuracySec=1s
        Persistent=false

        [Install]
        WantedBy=timers.target
        EOF"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo chmod +x {{.REMOTE_PATH}}/{{.BINARY_NAME}}"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl daemon-reload"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl enable {{.SERVICE_NAME}}.timer"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl restart {{.SERVICE_NAME}}.timer"
      - echo "Deployment complete! Check status with 'task status'"

  status:
    desc: Check scheduler status on remote server
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl status {{.SERVICE_NAME}}.timer"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl list-timers {{.SERVICE_NAME}}.timer"

  logs:
    desc: View scheduler logs on remote server
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
      LINES: '{{.LINES | default "50"}}'
    cmds:
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo journalctl -u {{.SERVICE_NAME}}.service -n {{.LINES}} --no-pager"

  stop:
    desc: Stop and disable scheduler on remote server
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl stop {{.SERVICE_NAME}}.timer"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl disable {{.SERVICE_NAME}}.timer"
      - echo "Scheduler stopped and disabled"

  clean:
    desc: Remove deployment files from remote server
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl stop {{.SERVICE_NAME}}.timer"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl disable {{.SERVICE_NAME}}.timer"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo rm -f /etc/systemd/system/{{.SERVICE_NAME}}.service"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo rm -f /etc/systemd/system/{{.SERVICE_NAME}}.timer"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo rm -rf {{.REMOTE_PATH}}"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl daemon-reload"
      - echo "Deployment cleaned up"

  test-run:
    desc: Test run the scheduler once on remote server
    vars:
      USER: '{{.DEPLOY_USER | default "zhukov"}}'
      HOST: '{{.DEPLOY_HOST | default "10.39.101.79"}}'
      PORT: '{{.DEPLOY_PORT | default "22"}}'
    cmds:
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo systemctl start {{.SERVICE_NAME}}.service"
      - ssh -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo journalctl -u {{.SERVICE_NAME}}.service -n 50"
